### ISSUE TITLE
Download URL

### ISSUE THREAD

**Issue by bngsudheer** [feurix/hatop#4]
The URL is not working http://hatop.googlecode.com/files/hatop-0.7.7.tar.gz 
Is there an alternative URL to download hatop?

**Comment by earzur** [comment]
use github tarball feature ? 

https://github.com/feurix/hatop/archive/master.zip will get you a zip of the master branch
https://github.com/feurix/hatop/archive/v0.7.7.tar.gz will get you a tar of tag 0.7.7, which is what you're looking for ?

**Comment by bngsudheer** [comment]
I used the github tarball. Thanks.
